In [3]:
import cv2
import numpy as np
import pandas as pd

from joblib import load

name = input('input name: ')
index = pd.read_csv('../datasets/' + name + '-index.csv', sep=',')
label_text = index.values[:,1]

cap = cv2.VideoCapture(0)
detector = cv2.CascadeClassifier('../models/haarcascades/haarcascade_frontalface_default.xml')
clf = load('../models/svm-' + name + '.mdl')

while(cap.isOpened()):
    ret, frame = cap.read()
    if ret == True:
        img = frame.copy()
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        faces = detector.detectMultiScale(gray, 1.2, 4)

        for (x, y, w, h) in faces:
            images = []
            face = gray[y:y+h, x:x+w]
            rsz_face = cv2.resize(face, (64,64), interpolation=cv2.INTER_LINEAR)
            images.append(np.ravel(rsz_face))

            y_p = clf.predict(images)
            prob = clf.predict_proba(images)

            text = label_text[int(y_p)] + ' ({0:.3g}'.format(max_prob * 100) + '%)'
            
            cv2.putText(img, text, (x,y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,255,0), thickness=2)
            cv2.rectangle(img, (x,y), (x+w,y+h), (0,255,0), 2)
        cv2.imshow('Face Recognition System', img)

        if cv2.waitKey(1) & 0xFF == ord(' '):
            break
    else:
        break
cap.release()
cv2.destroyAllWindows()

[[0.52742632 0.47257368]]
[[0.52201293 0.47798707]]
[[0.52261588 0.47738412]]
[[0.5 0.5]]
[[0.5 0.5]]
[[0.4645042 0.5354958]]
[[0.48842915 0.51157085]]
[[0.48962201 0.51037799]]
[[0.38945751 0.61054249]]
[[0.32056639 0.67943361]]
[[0.37862848 0.62137152]]
[[0.32785953 0.67214047]]
[[0.24525265 0.75474735]]
[[0.25709087 0.74290913]]
[[0.2508381 0.7491619]]
[[0.21082229 0.78917771]]
[[0.30291786 0.69708214]]
[[0.26965138 0.73034862]]
[[0.25236527 0.74763473]]
[[0.28673741 0.71326259]]
[[0.28489697 0.71510303]]
[[0.29679451 0.70320549]]
[[0.32347681 0.67652319]]
[[0.3269729 0.6730271]]
[[0.32750214 0.67249786]]
[[0.30816133 0.69183867]]
[[0.32921512 0.67078488]]
[[0.31549729 0.68450271]]
[[0.31719579 0.68280421]]
[[0.32655282 0.67344718]]
[[0.34759543 0.65240457]]
[[0.36366056 0.63633944]]
[[0.35087258 0.64912742]]
[[0.33882273 0.66117727]]
[[0.30804943 0.69195057]]
[[0.3953907 0.6046093]]
[[0.36443422 0.63556578]]
[[0.28330169 0.71669831]]
[[0.37942833 0.62057167]]
[[0.3324333 0.6675667]